# Imports

In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
raw_data = np.loadtxt('Dow_061719_061720.csv', delimiter=',', usecols=(6,7,8,9,10,11,12))
raw_data

array([[ 9.9000500e-01,  5.1060140e-03,  3.3200360e-01, ...,
         3.0004800e-02,  1.5153500e-04,  1.0000000e+00],
       [ 9.9000500e-01,  5.1060140e-03,  3.3200360e-01, ...,
         3.0004800e-02,  1.5153500e-04,  1.0000000e+00],
       [ 2.3999940e+00,  1.2093696e-02,  3.3200360e-01, ...,
         3.0004800e-02,  1.5153500e-04,  0.0000000e+00],
       ...,
       [-8.7000300e-01, -1.8443991e-02, -4.2199940e-01, ...,
         1.4100020e-01,  2.8354860e-03,  1.0000000e+00],
       [ 1.7900010e+00,  3.7972020e-02, -8.8200000e-01, ...,
        -1.1000200e-02, -2.2083000e-04,  0.0000000e+00],
       [-1.3699990e+00, -2.8423215e-02, -5.2800000e-01, ...,
         7.2000000e-02,  1.4428280e-03,  0.0000000e+00]])

In [3]:
unscaled_inputs = raw_data[:,0:-1]
targets = raw_data[:,-1]

In [4]:
unscaled_inputs

array([[ 9.9000500e-01,  5.1060140e-03,  3.3200360e-01,  1.6794150e-03,
         3.0004800e-02,  1.5153500e-04],
       [ 9.9000500e-01,  5.1060140e-03,  3.3200360e-01,  1.6794150e-03,
         3.0004800e-02,  1.5153500e-04],
       [ 2.3999940e+00,  1.2093696e-02,  3.3200360e-01,  1.6794150e-03,
         3.0004800e-02,  1.5153500e-04],
       ...,
       [-8.7000300e-01, -1.8443991e-02, -4.2199940e-01, -8.3643740e-03,
         1.4100020e-01,  2.8354860e-03],
       [ 1.7900010e+00,  3.7972020e-02, -8.8200000e-01, -1.8025014e-02,
        -1.1000200e-02, -2.2083000e-04],
       [-1.3699990e+00, -2.8423215e-02, -5.2800000e-01, -1.1030333e-02,
         7.2000000e-02,  1.4428280e-03]])

In [5]:
targets

array([1., 1., 0., ..., 1., 0., 0.])

# Shuffle the data

In [6]:
shuffled_indices = np.arange(unscaled_inputs.shape[0])
np.random.shuffle(shuffled_indices)

shuffled_inputs = unscaled_inputs[shuffled_indices]
shuffled_targets = targets[shuffled_indices]

# Balance the Dataset

In [7]:
shuffled_inputs.shape[0]

7366

In [8]:
num_one_targets = int(np.sum(shuffled_targets))
num_one_targets

3643

In [9]:
3643/7366

0.4945696443117024

The dataset appears already balanced

# Standardize the inputs

In [10]:
scaled_inputs = preprocessing.scale(shuffled_inputs)

# Split the dataset into train, validation, and test

In [11]:
samples_count = scaled_inputs.shape[0]

In [12]:
train_samples_count = int(0.8*samples_count)
validation_samples_count = int(0.1*samples_count)
test_samples_count = samples_count - train_samples_count - validation_samples_count

train_inputs = scaled_inputs[:train_samples_count]
train_targets = shuffled_targets[:train_samples_count]

validation_inputs = scaled_inputs[train_samples_count:train_samples_count+validation_samples_count]
validation_targets = shuffled_targets[train_samples_count:train_samples_count+validation_samples_count]

test_inputs = scaled_inputs[train_samples_count+validation_samples_count:]
test_targets = shuffled_targets[train_samples_count+validation_samples_count:]

print(train_samples_count, validation_samples_count, test_samples_count)

5892 736 738


# Save the three datasets in *.npz

In [13]:
np.savez('data_train', inputs=train_inputs, targets=train_targets)
np.savez('data_validation', inputs=validation_inputs, targets=validation_targets)
np.savez('data_test', inputs=test_inputs, targets=test_targets)